// Package ui embeds the compiled React dashboard into the Go binary.
// The dist/ directory is generated by running `make build-ui` (pnpm build in ui/web/).
//
// Usage:
//   - Development:  run `pnpm dev` in ui/web/, set VITE_BACKEND_PORT=11093
//   - Production:   run `make build-full` to embed the UI into the binary
package ui

import (
	"embed"
	"io/fs"
	"log/slog"
	"net/http"
	"strings"
)

// dist holds the compiled Vite output.
// `make build-ui` copies ui/web/dist → internal/ui/dist before `go build`.
//
//go:embed dist
var dist embed.FS

// Handler returns an http.Handler that serves the embedded SPA.
// API paths (/v1/, /ws, /health) are left to other mux entries.
// All other paths fall back to index.html for React Router (SPA routing).
func Handler() http.Handler {
	sub, err := fs.Sub(dist, "dist")
	if err != nil {
		slog.Warn("ui: failed to sub embed fs", "error", err)
		return http.NotFoundHandler()
	}
	fileServer := http.FileServer(http.FS(sub))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := strings.TrimPrefix(r.URL.Path, "/")
		if path == "" {
			path = "index.html"
		}

		// Check if the file exists in the embed FS
		f, err := dist.Open("dist/" + path)
		if err != nil {
			// Not a static asset → serve index.html for client-side routing
			r2 := r.Clone(r.Context())
			r2.URL.Path = "/index.html"
			fileServer.ServeHTTP(w, r2)
			return
		}
		f.Close()

		fileServer.ServeHTTP(w, r)
	})
}

// Available returns true if dist/ contains a real Vite build (has assets/ dir).
// Returns false for the placeholder stub, so the gateway skips mounting
// and logs a helpful message instead.
func Available() bool {
	entries, err := dist.ReadDir("dist/assets")
	return err == nil && len(entries) > 0
}
